# FOME simulator build Docker image

ARG UBUNTU_VERSION=22.04
FROM fome/build-base:ubuntu-${UBUNTU_VERSION}

ARG FOME_DIR=/fome
ARG PROJECT_BOARD
ENV PROJECT_BOARD=${PROJECT_BOARD:-}
ARG PROJECT_CPU
ENV PROJECT_CPU=${PROJECT_CPU:-}
ARG COMPILE_ARGS="PROJECT_BOARD=${PROJECT_BOARD} PROJECT_CPU=${PROJECT_CPU}"
ENV COMPILE_ARGS=${COMPILE_ARGS:-}

WORKDIR ${FOME_DIR}

WORKDIR ./fome/simulator
ENTRYPOINT ["sh", "-c", "./compile.sh ${COMPILE_ARGS}"]
